<HTML>
<HEAD>
<TITLE>print [</TITLE>
</HEAD>
<BODY BGCOLOR="#fffff8" TEXT="#000000">
<H1><A NAME="NAME">NAME

</A></H1>

<P><B>print</B> [-n] <I>file</I>

</P><H1><A NAME="DESCRIPTION">DESCRIPTION

</A></H1>

<P>=head1 introduces a 1st level heading.
<B>print</B> sends <I>file</I> to a printer.
<B>bold</B>, <I>italic</I>, zero, <B>bold, <I>bold italic</I>, bold</B> normal.
Non-breaking&nbsp;space, <CODE>0</CODE>.

</P>
<P><CODE>code</CODE>, <B>bold <CODE>code</CODE></B>, <I>file</I>, <A NAME="index">index</A>
&lt;, &gt;, /, |, A, &Agrave;
<B>&lt;, &gt;, /, |, A, &Agrave;</B>
<I><B>&lt;, &gt;, /, |, A, &Agrave;</B></I>

</P>
<P>&copy; &deg; &divide; &frac12; &micro; &middot; &not; &reg; &times;

</P>
<P><CODE>$a &lt;=&gt; $b</CODE>,
<CODE>$a &lt;=&gt; $b</CODE>

</P>
<P><CODE><B>$foo-&gt;bar</B></CODE>,
<I> <CODE><B>$foo-&gt;bar</B></CODE> </I>,

</P>
<P>An <CODE><A HREF="page.html#section">page/section</A></CODE> markup.

</P>
<P><CODE>$a &lt;&lt; $b</CODE>,
<B> <CODE>$a &gt;&gt; $b</CODE> </B>;

</P>
<P>see <A HREF="#(%3f%3epattern)"><CODE>(?&gt;pattern)</CODE></A>.

</P>
<P>see <A HREF="#(%3f%3epattern)">No backtracking</A>.

</P>
<P><CODE><B><I>Italic Bold Code</I></B></CODE>
</P>
</BODY>
</HTML>
